### ISSUE TITLE
Tooltips overlap when hovering the mouse on the "Database name" field for oracle-12

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#147]
Hi guys,

Suggesting a trivial improvement (in the way you prefer) for the 2 tooltips on the disabled **Database name** field for **oracle-12** engine, as they overlap each other. Steps:

1) Navigate to http://cloud-db.liferay.int/createdb
2) **Database**: select **oracle-12**
3) Hover the mouse on **Database name** field:

![image](https://user-images.githubusercontent.com/7203657/28072460-61750a04-6653-11e7-8b3d-98c29d7ff62c.png)

Thanks !

**Comment by sorin-pop** [comment]
Yep, I recently noticed this as well. I think initially we only had the one on the right (the square one), I remember as I implemented it, the other one seems to be new... I'm sure david will handle it perfectly.

**Comment by alfonsocrisci** [comment]
Thanks guys ! I checked and I still see the issue (incognito, FF and Chrome). Is the bugfix supposed to take effect in the future?

**Comment by balcsida** [comment]
Hi @alfonsocrisci,

This bugfix is not released yet, as there was no new version released.
As soon as @djavorszky comes back from his vacation, he will handle the release.

**Comment by alfonsocrisci** [comment]
Great - no need to rush at all ! Thank you ! :)
